// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwEPSEQmKEP6BpTerfO4wIzjq2XaodVtk',
    appId: '1:492374336865:web:bcea0032b391bd15e99120',
    messagingSenderId: '492374336865',
    projectId: 'fir-project-725c4',
    authDomain: 'fir-project-725c4.firebaseapp.com',
    storageBucket: 'fir-project-725c4.appspot.com',
    measurementId: 'G-TRPQPNV9T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5WCEg2C0BxMAsOoCn3VUW600xE-iDy1Q',
    appId: '1:492374336865:android:dc2417e15793412de99120',
    messagingSenderId: '492374336865',
    projectId: 'fir-project-725c4',
    storageBucket: 'fir-project-725c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjJk69ZNfW0XZruysxs0hqksi_5AJIrOQ',
    appId: '1:492374336865:ios:4e9d336ffac4aee7e99120',
    messagingSenderId: '492374336865',
    projectId: 'fir-project-725c4',
    storageBucket: 'fir-project-725c4.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjJk69ZNfW0XZruysxs0hqksi_5AJIrOQ',
    appId: '1:492374336865:ios:4e9d336ffac4aee7e99120',
    messagingSenderId: '492374336865',
    projectId: 'fir-project-725c4',
    storageBucket: 'fir-project-725c4.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
